version = 1

[[annotations]]
path = ["neumorphicpanel/qml/CloudyRectMaterial/CloudyRectMaterial.qep",
        "testbed/qml/CustomMultiEffect/CustomMultiEffect.qep"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR BSD-3-Clause"
